#!/bin/bash
set -ex

for target in latest s3 docker docker-s3 postgres postgres-s3 docker-postgres; do
  docker image build \
    --build-arg VCS_REF="$GIT_SHA1" \
    --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
    --tag "$DOCKER_REPO:$target" \
    --target "$target" \
    .
done
